language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install cython # Hack to get pyyaml to compile under 3.7
  - pip install -e .
before_script:
  # Get the linting outputs, but don't fail if they're poor
  - megaqc lint || true
script: megaqc test
